"""Add mcp, a2a objs, chat history

Revision ID: 2039a13eadcf
Revises: a2d715381000
Create Date: 2025-05-29 16:13:13.650708

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2039a13eadcf"
down_revision: Union[str, None] = "a2d715381000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "a2acards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("server_url", sa.String(), nullable=False),
        sa.Column(
            "card_content", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("creator_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_a2acards_creator_id"), "a2acards", ["creator_id"], unique=False
    )
    op.create_index(op.f("ix_a2acards_id"), "a2acards", ["id"], unique=False)
    op.create_table(
        "chatconversations",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("creator_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_chatconversations_creator_id"),
        "chatconversations",
        ["creator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chatconversations_session_id"),
        "chatconversations",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "mcpservers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("server_url", sa.String(), nullable=False),
        sa.Column("mcp_tools", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "mcp_prompts", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "mcp_resources", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("creator_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mcpservers_creator_id"), "mcpservers", ["creator_id"], unique=False
    )
    op.create_index(op.f("ix_mcpservers_id"), "mcpservers", ["id"], unique=False)
    op.create_table(
        "chatmessages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "sender_type",
            sa.Enum("user", "master_agent", name="sendertype"),
            nullable=False,
        ),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "extra_metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["chatconversations.session_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chatmessages_conversation_id"),
        "chatmessages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_chatmessages_id"), "chatmessages", ["id"], unique=False)
    op.add_column("agents", sa.Column("alias", sa.String(), nullable=False))
    op.create_unique_constraint(None, "agents", ["alias"])
    op.add_column("agentworkflows", sa.Column("alias", sa.String(), nullable=False))
    op.create_unique_constraint(None, "agentworkflows", ["alias"])
    op.add_column("modelconfigs", sa.Column("user_prompt", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modelconfigs", "user_prompt")
    op.drop_constraint(None, "agentworkflows", type_="unique")
    op.drop_column("agentworkflows", "alias")
    op.drop_constraint(None, "agents", type_="unique")
    op.drop_column("agents", "alias")
    op.drop_index(op.f("ix_chatmessages_id"), table_name="chatmessages")
    op.drop_index(op.f("ix_chatmessages_conversation_id"), table_name="chatmessages")
    op.drop_table("chatmessages")
    op.drop_index(op.f("ix_mcpservers_id"), table_name="mcpservers")
    op.drop_index(op.f("ix_mcpservers_creator_id"), table_name="mcpservers")
    op.drop_table("mcpservers")
    op.drop_index(
        op.f("ix_chatconversations_session_id"), table_name="chatconversations"
    )
    op.drop_index(
        op.f("ix_chatconversations_creator_id"), table_name="chatconversations"
    )
    op.drop_table("chatconversations")
    op.drop_index(op.f("ix_a2acards_id"), table_name="a2acards")
    op.drop_index(op.f("ix_a2acards_creator_id"), table_name="a2acards")
    op.drop_table("a2acards")
    # ### end Alembic commands ###
