"""Unique provider name per user

Revision ID: 2110cd47ce48
Revises: 234ef98c5f90
Create Date: 2025-06-13 14:42:08.238141

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2110cd47ce48"
down_revision: Union[str, None] = "234ef98c5f90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("modelproviders_name_key", "modelproviders", type_="unique")
    op.create_unique_constraint(
        "uq_user_item_name", "modelproviders", ["creator_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_item_name", "modelproviders", type_="unique")
    op.create_unique_constraint("modelproviders_name_key", "modelproviders", ["name"])
    # ### end Alembic commands ###
