"""provider O2M modelconfig

Revision ID: 234ef98c5f90
Revises: 37678785bf33
Create Date: 2025-06-12 19:31:21.135013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234ef98c5f90'
down_revision: Union[str, None] = '37678785bf33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelproviders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_modelproviders_creator_id'), 'modelproviders', ['creator_id'], unique=False)
    op.create_index(op.f('ix_modelproviders_id'), 'modelproviders', ['id'], unique=False)
    op.add_column('modelconfigs', sa.Column('provider_id', sa.UUID(), nullable=True))
    op.alter_column('modelconfigs', 'user_prompt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_modelconfigs_provider', table_name='modelconfigs')
    op.create_index(op.f('ix_modelconfigs_provider_id'), 'modelconfigs', ['provider_id'], unique=False)
    op.create_foreign_key(None, 'modelconfigs', 'modelproviders', ['provider_id'], ['id'], ondelete='CASCADE')
    op.drop_column('modelconfigs', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modelconfigs', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'modelconfigs', type_='foreignkey')
    op.drop_index(op.f('ix_modelconfigs_provider_id'), table_name='modelconfigs')
    op.create_index('ix_modelconfigs_provider', 'modelconfigs', ['provider'], unique=False)
    op.alter_column('modelconfigs', 'user_prompt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('modelconfigs', 'provider_id')
    op.drop_index(op.f('ix_modelproviders_id'), table_name='modelproviders')
    op.drop_index(op.f('ix_modelproviders_creator_id'), table_name='modelproviders')
    op.drop_table('modelproviders')
    # ### end Alembic commands ###
