"""created_at fields in mcptools

Revision ID: 37678785bf33
Revises: 9f36a10bd389
Create Date: 2025-06-12 14:07:45.877772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37678785bf33'
down_revision: Union[str, None] = '9f36a10bd389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcptools', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('mcptools', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcptools', 'updated_at')
    op.drop_column('mcptools', 'created_at')
    # ### end Alembic commands ###
