"""Update a2a, mcp models

Revision ID: 56aa0b6c1e46
Revises: c99fda6679aa
Create Date: 2025-06-03 20:07:26.891516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56aa0b6c1e46'
down_revision: Union[str, None] = 'c99fda6679aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'a2acards', ['server_url'])
    op.create_unique_constraint(None, 'mcpservers', ['server_url'])
    op.drop_column('mcpservers', 'mcp_prompts')
    op.drop_column('mcpservers', 'mcp_resources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcpservers', sa.Column('mcp_resources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('mcpservers', sa.Column('mcp_prompts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mcpservers', type_='unique')
    op.drop_constraint(None, 'a2acards', type_='unique')
    # ### end Alembic commands ###
