"""Unique config per user per config

Revision ID: 59f4659c7814
Revises: 8403bb364491
Create Date: 2025-07-08 11:56:19.398406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f4659c7814'
down_revision: Union[str, None] = '8403bb364491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('modelconfigs_name_key', 'modelconfigs', type_='unique')
    op.create_unique_constraint('uq_user_config_name', 'modelconfigs', ['creator_id', 'name'])
    op.drop_constraint('uq_user_item_name', 'modelproviders', type_='unique')
    op.create_unique_constraint('uq_user_provider_name', 'modelproviders', ['creator_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_provider_name', 'modelproviders', type_='unique')
    op.create_unique_constraint('uq_user_item_name', 'modelproviders', ['creator_id', 'name'])
    op.drop_constraint('uq_user_config_name', 'modelconfigs', type_='unique')
    op.create_unique_constraint('modelconfigs_name_key', 'modelconfigs', ['name'])
    # ### end Alembic commands ###
