"""Provider metadata

Revision ID: 5c2cb0d747c2
Revises: cfb56bfefc18
Create Date: 2025-06-16 12:27:21.126196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c2cb0d747c2'
down_revision: Union[str, None] = 'cfb56bfefc18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modelproviders', sa.Column('provider_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modelproviders', 'provider_metadata')
    # ### end Alembic commands ###
