"""Add request ID to Chat Message table

Revision ID: 9f36a10bd389
Revises: b1d2446494fc
Create Date: 2025-06-10 18:58:24.567263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f36a10bd389'
down_revision: Union[str, None] = 'b1d2446494fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessages', sa.Column('request_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatmessages', 'request_id')
    # ### end Alembic commands ###
