"""max_last_messages nullable false

Revision ID: b1d2446494fc
Revises: bc8a40747860
Create Date: 2025-06-09 18:15:13.794224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d2446494fc'
down_revision: Union[str, None] = 'bc8a40747860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modelconfigs', 'max_last_messages',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modelconfigs', 'max_last_messages',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
