"""Move max_last_messages param into modelconfig

Revision ID: bc8a40747860
Revises: c1dabd9cf307
Create Date: 2025-06-05 19:26:57.707472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8a40747860'
down_revision: Union[str, None] = 'c1dabd9cf307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modelconfigs', sa.Column('max_last_messages', sa.Integer(), nullable=True))
    op.drop_column('userprofiles', 'max_last_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofiles', sa.Column('max_last_messages', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('modelconfigs', 'max_last_messages')
    # ### end Alembic commands ###
