"""O2M mcp_tool

Revision ID: c1dabd9cf307
Revises: 56aa0b6c1e46
Create Date: 2025-06-05 18:06:37.683446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1dabd9cf307'
down_revision: Union[str, None] = '56aa0b6c1e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcptools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('inputSchema', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('annotations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('mcp_server_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcpservers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcptools_id'), 'mcptools', ['id'], unique=False)
    op.create_index(op.f('ix_mcptools_mcp_server_id'), 'mcptools', ['mcp_server_id'], unique=False)
    op.drop_column('mcpservers', 'mcp_tools')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcpservers', sa.Column('mcp_tools', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_mcptools_mcp_server_id'), table_name='mcptools')
    op.drop_index(op.f('ix_mcptools_id'), table_name='mcptools')
    op.drop_table('mcptools')
    # ### end Alembic commands ###
