"""Add user profile

Revision ID: c99fda6679aa
Revises: 2039a13eadcf
Create Date: 2025-06-02 10:51:42.355263

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c99fda6679aa"
down_revision: Union[str, None] = "2039a13eadcf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userprofiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("max_last_messages", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_userprofiles_id"), "userprofiles", ["id"], unique=False)
    op.create_index(
        op.f("ix_userprofiles_user_id"), "userprofiles", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userprofiles_user_id"), table_name="userprofiles")
    op.drop_index(op.f("ix_userprofiles_id"), table_name="userprofiles")
    op.drop_table("userprofiles")
    # ### end Alembic commands ###
