"""is_active field for flows

Revision ID: cfb56bfefc18
Revises: 2110cd47ce48
Create Date: 2025-06-13 16:02:49.597616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb56bfefc18'
down_revision: Union[str, None] = '2110cd47ce48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentworkflows', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agentworkflows', 'is_active')
    # ### end Alembic commands ###
